version: '3'

services:
  mlmariadbv2:
    image: mariadb:10.2
    networks:
      - mercadolivre-mariadb
    environment:
      #MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: mercadolivre


  mercadolivreimg:
    restart: always
    build:
      dockerfile: ./Dockerfile
      context: .
    image: mercadolivreimg
    ports:
      - 8083:8080
    networks:
      - mercadolivre-mariadb
    environment:
      DB_DATABASE: mercadolivre
      DB_USER: root
      DB_HOST: jdbc:mariadb://mlmariadbv2/mercadolivre
      DB_PASSWORD: password
    depends_on:
      - mlmariadbv2

networks:
  mercadolivre-mariadb:
    driver: bridge